lopenings:
         .byte   $0f
         .byte   $0d
         .byte   <@TBD52
         .byte   >@TBD52
         .byte   $0b
         .byte   <@TBE2B
         .byte   >@TBE2B
         .byte   $09
         .byte   <@TBEA6
         .byte   >@TBEA6
         .byte   $02
         .byte   <@TBF12
         .byte   >@TBF12
         .byte   $0f
         .byte   <@TBF45
         .byte   >@TBF45
@TBD52:  .byte   $3f
         .byte   $09
         .byte   <@TBD68
         .byte   >@TBD68
         .byte   $05
         .byte   <@TBDAB
         .byte   >@TBDAB
         .byte   $08
         .byte   <@TBDDE
         .byte   >@TBDDE
         .byte   $04
         .byte   <@TBDF7
         .byte   >@TBDF7
         .byte   $06
         .byte   <@TBE1C
         .byte   >@TBE1C
         .byte   $12
         .byte   <@TBE25
         .byte   >@TBE25
         .byte   $07
         .byte   <@TBE28
         .byte   >@TBE28
@TBD68:  .byte   $08
         .byte   $0d
         .byte   <@TBD6F
         .byte   >@TBD6F
         .byte   $18
         .byte   <@TBDA4
         .byte   >@TBDA4
@TBD6F:  .byte   $78
         .byte   $0f
         .byte   <@TBD7C
         .byte   >@TBD7C
         .byte   $1a
         .byte   <@TBD97
         .byte   >@TBD97
         .byte   $06
         .byte   $ff
         .byte   $09
         .byte   $ff
         .byte   $07
         .byte   $ff
@TBD7C:  .byte   $18
         .byte   $07
         .byte   <@TBD86
         .byte   >@TBD86
         .byte   $06
         .byte   <@TBD8F
         .byte   >@TBD8F
         .byte   $01
         .byte   <@TBD94
         .byte   >@TBD94
@TBD86:  .byte   $38
         .byte   $05
         .byte   $ff
         .byte   $0b
         .byte   $ff
         .byte   $18
         .byte   $ff
         .byte   $1b
         .byte   $ff
@TBD8F:  .byte   $02
         .byte   $19
         .byte   $ff
         .byte   $1c
         .byte   $ff
@TBD94:  .byte   $00
         .byte   $1c
         .byte   $ff
@TBD97:  .byte   $06
         .byte   $11
         .byte   <@TBD9F
         .byte   >@TBD9F
         .byte   $01
         .byte   $ff
         .byte   $17
         .byte   $ff
@TBD9F:  .byte   $01
         .byte   $01
         .byte   $ff
         .byte   $00
         .byte   $ff
@TBDA4:  .byte   $00
         .byte   $00
         .byte   <@TBDA8
         .byte   >@TBDA8
@TBDA8:  .byte   $00
         .byte   $0e
         .byte   $ff
@TBDAB:  .byte   $08
         .byte   $0d
         .byte   <@TBDB2
         .byte   >@TBDB2
         .byte   $01
         .byte   <@TBDDB
         .byte   >@TBDDB
@TBDB2:  .byte   $19
         .byte   $05
         .byte   <@TBDBF
         .byte   >@TBDBF
         .byte   $10
         .byte   <@TBDC6
         .byte   >@TBDC6
         .byte   $07
         .byte   <@TBDCD
         .byte   >@TBDCD
         .byte   $14
         .byte   <@TBDD4
         .byte   >@TBDD4
@TBDBF:  .byte   $00
         .byte   $11
         .byte   <@TBDC3
         .byte   >@TBDC3
@TBDC3:  .byte   $00
         .byte   $00
         .byte   $ff
@TBDC6:  .byte   $00
         .byte   $11
         .byte   <@TBDCA
         .byte   >@TBDCA
@TBDCA:  .byte   $00
         .byte   $00
         .byte   $ff
@TBDCD:  .byte   $00
         .byte   $11
         .byte   <@TBDD1
         .byte   >@TBDD1
@TBDD1:  .byte   $00
         .byte   $00
         .byte   $ff
@TBDD4:  .byte   $00
         .byte   $1b
         .byte   <@TBDD8
         .byte   >@TBDD8
@TBDD8:  .byte   $00
         .byte   $02
         .byte   $ff
@TBDDB:  .byte   $00
         .byte   $10
         .byte   $ff
@TBDDE:  .byte   $00
         .byte   $16
         .byte   <@TBDE2
         .byte   >@TBDE2
@TBDE2:  .byte   $00
         .byte   $08
         .byte   <@TBDE6
         .byte   >@TBDE6
@TBDE6:  .byte   $02
         .byte   $01
         .byte   <@TBDED
         .byte   >@TBDED
         .byte   $02
         .byte   <@TBDF2
         .byte   >@TBDF2
@TBDED:  .byte   $02
         .byte   $1d
         .byte   $ff
         .byte   $1f
         .byte   $ff
@TBDF2:  .byte   $02
         .byte   $1f
         .byte   $ff
         .byte   $07
         .byte   $ff
@TBDF7:  .byte   $08
         .byte   $16
         .byte   <@TBDFE
         .byte   >@TBDFE
         .byte   $0d
         .byte   <@TBE15
         .byte   >@TBE15
@TBDFE:  .byte   $00
         .byte   $06
         .byte   <@TBE02
         .byte   >@TBE02
@TBE02:  .byte   $0a
         .byte   $01
         .byte   <@TBE0C
         .byte   >@TBE0C
         .byte   $24
         .byte   <@TBE0F
         .byte   >@TBE0F
         .byte   $25
         .byte   <@TBE12
         .byte   >@TBE12
@TBE0C:  .byte   $00
         .byte   $00
         .byte   $ff
@TBE0F:  .byte   $00
         .byte   $00
         .byte   $ff
@TBE12:  .byte   $00
         .byte   $10
         .byte   $ff
@TBE15:  .byte   $00
         .byte   $06
         .byte   <@TBE19
         .byte   >@TBE19
@TBE19:  .byte   $00
         .byte   $01
         .byte   $ff
@TBE1C:  .byte   $00
         .byte   $16
         .byte   <@TBE20
         .byte   >@TBE20
@TBE20:  .byte   $02
         .byte   $19
         .byte   $ff
         .byte   $0b
         .byte   $ff
@TBE25:  .byte   $00
         .byte   $1d
         .byte   $ff
@TBE28:  .byte   $00
         .byte   $1d
         .byte   $ff
@TBE2B:  .byte   $09
         .byte   $12
         .byte   <@TBE35
         .byte   >@TBE35
         .byte   $07
         .byte   <@TBE64
         .byte   >@TBE64
         .byte   $0b
         .byte   <@TBE95
         .byte   >@TBE95
@TBE35:  .byte   $00
         .byte   $12
         .byte   <@TBE39
         .byte   >@TBE39
@TBE39:  .byte   $01
         .byte   $0d
         .byte   <@TBE40
         .byte   >@TBE40
         .byte   $0f
         .byte   <@TBE4F
         .byte   >@TBE4F
@TBE40:  .byte   $02
         .byte   $01
         .byte   <@TBE47
         .byte   >@TBE47
         .byte   $0e
         .byte   <@TBE4A
         .byte   >@TBE4A
@TBE47:  .byte   $00
         .byte   $19
         .byte   $ff
@TBE4A:  .byte   $08
         .byte   $08
         .byte   $ff
         .byte   $19
         .byte   $ff
@TBE4F:  .byte   $18
         .byte   $01
         .byte   <@TBE59
         .byte   >@TBE59
         .byte   $18
         .byte   <@TBE5E
         .byte   >@TBE5E
         .byte   $0e
         .byte   <@TBE61
         .byte   >@TBE61
@TBE59:  .byte   $02
         .byte   $14
         .byte   $ff
         .byte   $0d
         .byte   $ff
@TBE5E:  .byte   $00
         .byte   $0d
         .byte   $ff
@TBE61:  .byte   $00
         .byte   $14
         .byte   $ff
@TBE64:  .byte   $00
         .byte   $12
         .byte   <@TBE68
         .byte   >@TBE68
@TBE68:  .byte   $0a
         .byte   $07
         .byte   <@TBE72
         .byte   >@TBE72
         .byte   $05
         .byte   <@TBE81
         .byte   >@TBE81
         .byte   $00
         .byte   <@TBE8E
         .byte   >@TBE8E
@TBE72:  .byte   $08
         .byte   $01
         .byte   <@TBE79
         .byte   >@TBE79
         .byte   $18
         .byte   <@TBE7E
         .byte   >@TBE7E
@TBE79:  .byte   $02
         .byte   $1f
         .byte   $ff
         .byte   $07
         .byte   $ff
@TBE7E:  .byte   $00
         .byte   $1f
         .byte   $ff
@TBE81:  .byte   $08
         .byte   $0e
         .byte   <@TBE88
         .byte   >@TBE88
         .byte   $1c
         .byte   <@TBE8B
         .byte   >@TBE8B
@TBE88:  .byte   $00
         .byte   $1b
         .byte   $ff
@TBE8B:  .byte   $00
         .byte   $00
         .byte   $ff
@TBE8E:  .byte   $00
         .byte   $0e
         .byte   <@TBE92
         .byte   >@TBE92
@TBE92:  .byte   $00
         .byte   $1c
         .byte   $ff
@TBE95:  .byte   $02
         .byte   $12
         .byte   <@TBE9C
         .byte   >@TBE9C
         .byte   $14
         .byte   <@TBE9F
         .byte   >@TBE9F
@TBE9C:  .byte   $00
         .byte   $12
         .byte   $ff
@TBE9F:  .byte   $00
         .byte   $00
         .byte   <@TBEA3
         .byte   >@TBEA3
@TBEA3:  .byte   $00
         .byte   $01
         .byte   $ff
@TBEA6:  .byte   $1b
         .byte   $05
         .byte   <@TBEB5
         .byte   >@TBEB5
         .byte   $09
         .byte   <@TBECC
         .byte   >@TBECC
         .byte   $08
         .byte   <@TBEF5
         .byte   >@TBEF5
         .byte   $04
         .byte   <@TBF06
         .byte   >@TBF06
         ;.byte   $12    ; CP/M version has a $12 here. Bug in VIC-20 version?
         .byte   <@TBF0D
         .byte   >@TBF0D
@TBEB5:  .byte   $01
         .byte   $01
         .byte   <@TBEBC
         .byte   >@TBEBC
         .byte   $05
         .byte   <@TBF53
         .byte   >@TBF53
@TBEBC:  .byte   $02
         .byte   $0f
         .byte   <@TBEC3
         .byte   >@TBEC3
         .byte   $13
         .byte   <@TBF50
         .byte   >@TBF50
@TBEC3:  .byte   $08
         .byte   $10
         .byte   <@TBEC9
         .byte   >@TBEC9
         .byte   $04
         .byte   $ff
@TBEC9:  .byte   $00
         .byte   $0f
         .byte   $ff
@TBECC:  .byte   $00
         .byte   $01
         .byte   <@TBED0
         .byte   >@TBED0
@TBED0:  .byte   $03
         .byte   $10
         .byte   <@TBEDA
         .byte   >@TBEDA
         .byte   $1b
         .byte   <@TBEE3
         .byte   >@TBEE3
         .byte   $07
         .byte   <@TBEF2
         .byte   >@TBEF2
@TBEDA:  .byte   $01
         .byte   $10
         .byte   <@TBEE0
         .byte   >@TBEE0
         .byte   $04
         .byte   $ff
@TBEE0:  .byte   $00
         .byte   $0e
         .byte   $ff
@TBEE3:  .byte   $01
         .byte   $10
         .byte   <@TBEEA
         .byte   >@TBEEA
         .byte   $04
         .byte   <@TBEEF
         .byte   >@TBEEF
@TBEEA:  .byte   $01
         .byte   $0e
         .byte   $ff
         .byte   $0a
         .byte   $ff
@TBEEF:  .byte   $00
         .byte   $13
         .byte   $ff
@TBEF2:  .byte   $00
         .byte   $10
         .byte   $ff
@TBEF5:  .byte   $00
         .byte   $05
         .byte   <@TBEF9
         .byte   >@TBEF9
@TBEF9:  .byte   $00
         .byte   $1b
         .byte   <@TBEFD
         .byte   >@TBEFD
@TBEFD:  .byte   $02
         .byte   $0e
         .byte   <@TBF03
         .byte   >@TBF03
         .byte   $0d
         .byte   $ff
@TBF03:  .byte   $00
         .byte   $0d
         .byte   $ff
@TBF06:  .byte   $00
         .byte   $05
         .byte   <@TBF0A
         .byte   >@TBF0A
@TBF0A:  .byte   $00
         .byte   $13
         .byte   $ff
@TBF0D:  .byte   $01
         .byte   $05
         .byte   $ff
         .byte   $01
         .byte   $ff
@TBF12:  .byte   $0a
         .byte   $07
         .byte   <@TBF1C
         .byte   >@TBF1C
         .byte   $05
         .byte   <@TBF37
         .byte   >@TBF37
         .byte   $12
         .byte   <@TBF42
         .byte   >@TBF42
@TBF1C:  .byte   $02
         .byte   $0d
         .byte   <@TBF23
         .byte   >@TBF23
         .byte   $08
         .byte   <@TBF34
         .byte   >@TBF34
@TBF23:  .byte   $02
         .byte   $06
         .byte   <@TBF2A
         .byte   >@TBF2A
         .byte   $1a
         .byte   <@TBF31
         .byte   >@TBF31
@TBF2A:  .byte   $00
         .byte   $02
         .byte   <@TBF2E
         .byte   >@TBF2E
@TBF2E:  .byte   $00
         .byte   $10
         .byte   $ff
@TBF31:  .byte   $00
         .byte   $02
         .byte   $ff
@TBF34:  .byte   $00
         .byte   $00
         .byte   $ff
@TBF37:  .byte   $00
         .byte   $0d
         .byte   <@TBF3B
         .byte   >@TBF3B
@TBF3B:  .byte   $00
         .byte   $10
         .byte   <@TBF3F
         .byte   >@TBF3F
@TBF3F:  .byte   $00
         .byte   $02
         .byte   $ff
@TBF42:  .byte   $00
         .byte   $0d
         .byte   $ff
@TBF45:  .byte   $00
         .byte   $07
         .byte   <@TBF49
         .byte   >@TBF49
@TBF49:  .byte   $00
         .byte   $03
         .byte   <@TBF4D
         .byte   >@TBF4D
@TBF4D:  .byte   $00
         .byte   $1a
         .byte   $ff
@TBF50:  .byte   $00
         .byte   $10
         .byte   $ff
@TBF53:  .byte   $00
         .byte   $13
         .byte   <@TBF57
         .byte   >@TBF57
@TBF57:  .byte   $02
         .byte   $0b
         .byte   <@TBF5D
         .byte   >@TBF5D
         .byte   $0e
         .byte   $ff
@TBF5D:  .byte   $00
         .byte   $00
         .byte   $ff
